name: electricdrive
favicon: null
layout_spectrum: 0.1103964380454272
typography_spectrum: 0.241007394855842
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7747090815100819
  lightness: 0.23301000334322453
  saturation: 0.8562433535698801
  rhythmicContrast: 0.9866200741380453
purpose: []
